apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tetra-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: tetra-deployment
  interval: 5m
  path: "./clusters/msl8r/apps/tetra-policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-tooling
    namespace: flux-system
