apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tetra-deployment
  namespace: flux
spec:
  interval: 5m
  path: "./clusters/msl8r/apps/tetra-deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-tooling
    namespace: flux