apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetra
  namespace: flux
spec:
  interval: 1m
  releaseName: tetra
  targetNamespace: tetra
  chart:
    spec:
      chart: tetragon
#      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: tetra
        namespace: flux
      interval: 1m
  values:
    replicaCount: 2
    enablePolicyFilter: "true"