apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetra
  namespace: tetra
spec:
  interval: 1m
  chart:
    spec:
      chart: tetragon
      version: '0.10.0'
      sourceRef:
        kind: HelmRepository
        name: tetra
#        namespace: tetra
      interval: 1m
  values:
    replicaCount: 2